name: ESFM
channels:
  - pytorch3d
  - pytorch
  - bottler
  - comet_ml
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aadict=0.2.3=pyh9f0ad1d_0
  - alsa-lib=1.2.3=h516909a_0
  - asset=0.6.13=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_1
  - blas=2.111=mkl
  - blas-devel=3.9.0=11_linux64_mkl
  - bokeh=2.4.0=py38h578d9bd_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py38h578d9bd_0
  - cffi=1.14.6=py38h3931269_1
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.3=py38h578d9bd_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cmake=3.21.3=h8897547_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - comet_ml=3.18.1=py38
  - configobj=5.0.6=py_0
  - cryptography=3.4.8=py38ha5dfef3_0
  - cudatoolkit=10.2.89=h8f6ccaa_9
  - cvxpy=1.1.15=py38h578d9bd_0
  - cvxpy-base=1.1.15=py38h43a58ef_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask=2021.9.1=pyhd8ed1ab_0
  - dask-core=2021.9.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - distributed=2021.9.1=py38h578d9bd_0
  - dulwich=0.20.25=py38h497a2fe_0
  - ecos=2.0.8=py38h6c62de6_1
  - eigen=3.4.0=h4bd325d_0
  - et_xmlfile=1.0.1=py_1001
  - everett=2.0.0=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.13.1=hba837de_1005
  - freeglut=3.2.1=h9c3ff4c_2
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.10.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20210804=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h82a94d6_10
  - gcc_linux-64=11.2.0=h39a9532_1
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - globre=0.1.5=pyh9f0ad1d_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gxx_impl_linux-64=11.2.0=h82a94d6_10
  - gxx_linux-64=11.2.0=hacbe6df_1
  - harfbuzz=3.0.0=h83ec7ef_1
  - hdf5=1.12.1=nompi_h2750804_101
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - iopath=0.1.8=pyhd8ed1ab_0
  - jasper=2.0.14=ha77e612_2
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.2=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.1.0=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_14
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_2
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.79.1=h2574ce0_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-devel_linux-64=11.2.0=h0952999_10
  - libgcc-ng=11.2.0=h1d223b6_10
  - libgfortran-ng=11.2.0=h69a702a_10
  - libgfortran5=11.2.0=h5c6108e_10
  - libglib=2.68.4=h174f98d_1
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_10
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_mkl
  - liblapacke=3.9.0=11_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.3=py38h66b0e6b_5
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_1
  - libprotobuf=3.18.1=h780b84a_0
  - libsanitizer=11.2.0=he4da1e4_10
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=11.2.0=h0952999_10
  - libstdcxx-ng=11.2.0=he4da1e4_10
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - metis=5.1.0=h58526e2_1006
  - mkl=2021.3.0=h726a3e6_557
  - mkl-devel=2021.3.0=ha770c72_558
  - mkl-include=2021.3.0=h726a3e6_557
  - mpfr=4.1.0=h9202a9a_1
  - msgpack-python=1.0.2=py38h1fd1430_1
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_1
  - numpy=1.21.2=py38he2449b9_0
  - nvidia-ml=7.352.0=py_0
  - nvidiacub=1.10.0=0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.3=py38h578d9bd_5
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1l=h7f98852_0
  - osqp=0.6.2=py38h43a58ef_2
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py38h43a58ef_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.3.2=py38h8e6f84c_0
  - pip=21.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plotly=5.3.1=pyhd8ed1ab_0
  - portalocker=2.3.2=py38h578d9bd_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.3=py38he5a9106_5
  - pycparser=2.20=pyh9f0ad1d_2
  - pyhocon=0.3.58=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.12=hb7a2778_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.7.0=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytorch3d=0.5.0=py38_cu102_pyt170
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_1
  - qdldl-python=0.1.5=py38h43a58ef_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-toolbelt=0.9.1=py_0
  - rhash=1.4.1=h7f98852_0
  - scipy=1.7.1=py38h56a6a73_0
  - scs=2.1.4=py38h6afa1d1_0
  - semantic_version=2.8.5=pyh9f0ad1d_0
  - setuptools=58.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.36.0=h9cd32fc_2
  - suitesparse=5.10.1=h9e50725_1
  - sysroot_linux-64=2.12=he073ed8_14
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tbb=2021.3.0=h4bd325d_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.1=py_0
  - torchvision=0.8.1=py38_cu102
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - websocket-client=0.57.0=py38h578d9bd_4
  - wheel=0.37.0=pyhd8ed1ab_1
  - wrapt=1.13.1=py38h497a2fe_0
  - wurlitzer=3.0.2=py38h578d9bd_0
  - x264=1!161.3030=h7f98852_1
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - zict=2.0.0=py_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
